version: '3.8'
services:
  pgdb:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "5432:5432"
#    volumes:
#      - ./sql/dump.sql:/docker-entrypoint-initdb.d/1_dump.sql
#      - ./sql/content.sql:/docker-entrypoint-initdb.d/2_content.sql
#      - ./sql/functions.sql:/docker-entrypoint-initdb.d/3_functions.sql
    networks:
      - database-network
#  dbeaver:
#    container_name: dbeaver_container
#    image: dbeaver/cloudbeaver
#    restart: always
#    depends_on:
#      -   pgdb
#    ports:
#      - "8080:8978"
#    networks:
#      - database-network
  redis-stack:
    container_name: redis_stack_container
    image: redis/redis-stack:latest
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
networks:
  database-network:
    driver: bridge
